# Generated by Django 4.1.7 on 2023-03-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sspanel', '0002_alter_account_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account',
            new_name='user',
        ),
    ]
