version: "3.9"
   
services:

  mq:
    image: rabbitmq:alpine
    restart: always

  worker:
    build: .
    command: python -m celery -A simple_sspanel worker -l INFO
    restart: always
    volumes:
      - .:/code
    environment:
      - DEBUG=False
    depends_on:
      - mq

  beat:
    build: .
    command: python -m celery -A simple_sspanel beat -l INFO
    restart: always
    volumes:
      - .:/code
    environment:
      - DEBUG=False
    depends_on:
      - mq

  web:
    build: .
    command: python -m gunicorn -b 0.0.0.0:8000 simple_sspanel.asgi:application -k uvicorn.workers.UvicornWorker
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000"
    environment:
      - DEBUG=False
    depends_on:
      - mq

  v2ray:
    image: v2fly/v2fly-core
    restart: always
    command: v2ray -c http://web:8000/internal/config
    depends_on:
      - web

  front:
    image: caddy:alpine
    restart: always
    volumes:
      - ./dependencies/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - static_volume:/staticfiles
      - caddy_data:/data
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "80"
      - "443"
    depends_on:
      - web
      - v2ray

volumes:
  static_volume:
  caddy_data:
