# Generated by Django 4.1.7 on 2023-03-18 04:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='Remark')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('server', models.CharField(help_text='Domain name or server address', max_length=128, unique=True, verbose_name='Server')),
                ('confirmed', models.BooleanField(default=False, help_text='Automatically discover the host, whether it has been confirmed, the confirmed host will receive the user configuration and use it', verbose_name='Confirmed')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('protocal', models.CharField(choices=[('vmess', 'vmess'), ('vless', 'vless'), ('trojan', 'trojan'), ('ssr', 'ssr'), ('ss', 'ss')], default='vmess', max_length=128, verbose_name='Protocal')),
                ('token', models.CharField(max_length=128, verbose_name='Token')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Level')),
                ('traffic_used', models.BigIntegerField(default=0, verbose_name='traffic used')),
                ('traffic_total', models.BigIntegerField(default=-1, verbose_name='traffic total')),
                ('traffic_weight', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=6, verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Proxy Node',
                'verbose_name_plural': 'Proxy Node',
            },
        ),
        migrations.CreateModel(
            name='UserTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='Remark')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('traffic_up', models.BigIntegerField(default=0, verbose_name='Upload traffic')),
                ('traffic_down', models.BigIntegerField(default=0, verbose_name='Download traffic')),
                ('proxy_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.proxynode', verbose_name='Traffic node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='System User')),
            ],
            options={
                'verbose_name': 'User traffic records',
                'verbose_name_plural': 'User traffic records',
            },
        ),
    ]
