# Generated by Django 4.1.7 on 2023-03-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sspanel', '0001_initial'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='Remark')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('traffic_up', models.BigIntegerField(default=0, verbose_name='Upload traffic')),
                ('traffic_down', models.BigIntegerField(default=0, verbose_name='Download traffic')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sspanel.account', verbose_name='sspanel account')),
                ('proxy_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.proxynode', verbose_name='Traffic node')),
            ],
            options={
                'verbose_name': 'User traffic records',
                'verbose_name_plural': 'User traffic records',
            },
        ),
        migrations.DeleteModel(
            name='UserTraffic',
        ),
    ]
