# Generated by Django 4.1.7 on 2023-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_accounttraffic_delete_usertraffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxynode',
            name='mirror',
            field=models.BooleanField(default=False, help_text='This node is the mirror image of other source nodes, but the domain name is different, please select', verbose_name='Mirror'),
        ),
    ]
