# Generated by Django 4.1.7 on 2023-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_proxynode_mirror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxynode',
            name='traffic_total',
            field=models.BigIntegerField(default=0, verbose_name='traffic total'),
        ),
    ]
